### ISSUE TITLE
Show number of Passed / Failed test scenario

### ISSUE THREAD

**Issue by arpit-nagar** [jan-molak/jenkins-build-monitor-plugin#228]
Hi @jan-molak ,
I installed this plugin and displaying jobs dashboard with this plugin.
I also installed Build Failure Analyzer  and claim Plugin. As it explains at [FAQ](https://github.com/jan-molak/jenkins-build-monitor-plugin/wiki/FAQ#how-do-i-know-what-tests-failed-the-build).
I want to show **Total: 143, Errors: 0, Failed: 0, Skipped: 0** which was in my build output
![13](https://cloud.githubusercontent.com/assets/16220515/15869081/6b6ea66c-2d08-11e6-8412-5ec80bd9606a.JPG)
I setup Build Failure Analyzer as 
![11](https://cloud.githubusercontent.com/assets/16220515/15869089/7b12dea8-2d08-11e6-9323-0d7ac8bae592.JPG)

Currently my Build monitor view is
![10](https://cloud.githubusercontent.com/assets/16220515/15869107/8f08fb86-2d08-11e6-8db7-995f9c9496ee.JPG)

But I want to show **Total: 143, Errors: 0, Failed: 0, Skipped: 0**
instead of 
3 builds have failed
Identified problem: TestFailure-XUnit

Can you please help me to solve this issue?

**Comment by arpit-nagar** [comment]
Hi @jan-molak, 
Any update on this?

**Comment by jan-molak** [comment]
Hey @arpit-nagar, looks like #148 should resolve the issue you describe (and close #170 too).
I'll merge #148 in and add some acceptance tests to demonstrate the functionality.

**Comment by arpit-nagar** [comment]
Thanks @jan-molak, :+1: 
Waiting for the release.

**Comment by arpit-nagar** [comment]
Hi @jan-molak ,
I have upgraded to latest plugin but still getting the same title.
How to setup description as you shown in your example?
Also is it possible to show html text as rendered html as shown in USG-Common?
![capture](https://cloud.githubusercontent.com/assets/16220515/16019375/428e96cc-31c6-11e6-89aa-5b291e825029.JPG)

**Comment by jan-molak** [comment]
Hey @arpit-nagar, did you have a chance to have a look at the example in ["Displaying the number of failed tests"](https://bitly.com/JBMSerenity) acceptance test?

---

There are three fields you can populate when defining a "failure cause": the name, the description and the comment. The description field handles placeholders such as `${1,2}`, which, as per the [Build Failure Analyzer documentation](https://wiki.jenkins-ci.org/display/JENKINS/Build+Failure+Analyzer#BuildFailureAnalyzer-Placeholdersindescription):

> [take the form of] `${I,G}`, where I is the indication number and G is the captured group within the indication expression. e.g., `${1,1}` would be replaced with the first indication's first captured group and `${1,2}` would be replaced with the first indication's second captured group.

To answer your second question: HTML is not supported as of yet.

Did that help?
J

**Comment by arpit-nagar** [comment]
Hi @jan-molak sorry to bother you again but I could not able to setup BFA plugin.
I set description ${1,1} and ${1,2} but I am getting output $1 and $2 respectively.
It may be very basic but I could not able to figure out how to setup. 
Can you please help me to setup it properly, My current configurations are:

![capture4](https://cloud.githubusercontent.com/assets/16220515/16127024/54fed016-3418-11e6-9d0c-cb63b662468e.JPG)

![capture3](https://cloud.githubusercontent.com/assets/16220515/16127031/5907906c-3418-11e6-83c6-f781f9091841.JPG)

![capture2](https://cloud.githubusercontent.com/assets/16220515/16127038/5f49a064-3418-11e6-8d93-d921af2d8c91.JPG)

**Comment by jan-molak** [comment]
Hey @arpit-nagar, it looks like you haven't defined the [capturing groups](http://www.regular-expressions.info/refcapture.html)? You'll need the parenthesis around `\d+` in your example.

As you can see in the acceptance test:
<img width="642" alt="screen shot 2016-06-17 at 13 42 23" src="https://cloud.githubusercontent.com/assets/1089173/16150834/8f52dc0c-3491-11e6-831f-e785e46fc623.png">

the regular expression goes like this:
```
.*Total: (\d+).*Failed: ([1-9]\d*).*
 ^         ^               ^       ^
(1)       (2)             (3)     (1)

Where:
(1) - I use `.*` because we don't care about the text preceding the word "Total", 
      or occurring after the number of failed tests.
(2) - (\d+) this defines the first capturing group to capture at least one digit
      Build Failure Analyzer will reference the first group as ${1,1} 
(3) - ([1-9]\d*) this defines a group to capture non-negative number
      Build Failure Analyzer will reference this second group as ${1,2} 
```

Let me know if that helped!

Best,
Jan

**Comment by arpit-nagar** [comment]
Thanks @jan-molak, :+1: 
It worked. :smile:

**Comment by jan-molak** [comment]
Sweet, good job! 😄

**Comment by vinodgangal** [comment]
@jan-molak @arpit-nagar  Hi Both,
I am struct at the same issue as @arpit-nagar  faced.
This is my test result:
![image](https://user-images.githubusercontent.com/3798493/30243004-28815464-95bf-11e7-8da7-40b287f83c72.png)

This is my Build Failure Analyser configuration:
![image](https://user-images.githubusercontent.com/3798493/30243014-4e326e32-95bf-11e7-892a-6bf227636ff6.png)


THis is my dashboard view: 
![image](https://user-images.githubusercontent.com/3798493/30243021-5f97c53c-95bf-11e7-899b-63ef11c36712.png)

Here on the Build Monitor view instead of seeing the Test Failues as the casue, i want to see the actual number of tests failed.

Please help
